// 30-year backtest on observations only (no forecasts): how often would each area have reached
// Danger, and did known historical floods trigger it in time? Writes docs/EVALUATION-results.md.
// Run after `npm run calibrate` (reuses its download cache): npx tsx scripts/backtest.mts
import fs from "node:fs";
import path from "node:path";
import { dailyRain, dailyDischarge } from "./lib.mjs";
import { areas, rainPoints, rainThresholds, riverThresholds, stations } from "../src/lib/data";
import { assessArea } from "../src/lib/risk";
import type { Inputs, Level } from "../src/lib/types";

const START = "1994-01-01";
const END = "2023-12-31";
const Q_START = "1984-01-01";

// Documented historical floods (date = approximate onset of damaging flooding). Sources in docs/EVALUATION.md.
const EVENTS = [
  { name: "Haor flash flood, Mar–Apr 2017", areas: ["sunamganj"], onset: "2017-03-30" },
  { name: "Brahmaputra–Jamuna flood, Aug 2017", areas: ["kurigram", "chilmari", "fulchhari", "islampur", "sirajganj"], onset: "2017-08-13" },
  { name: "Brahmaputra–Jamuna flood, Jul 2019", areas: ["kurigram", "chilmari", "fulchhari", "islampur", "sirajganj"], onset: "2019-07-13" },
  { name: "Brahmaputra–Jamuna flood, Jul 2020", areas: ["kurigram", "chilmari", "fulchhari", "islampur", "sirajganj"], onset: "2020-06-28" },
  { name: "Sylhet–Sunamganj flood, Jun 2022", areas: ["sunamganj", "chhatak", "companiganj", "gowainghat"], onset: "2022-06-15" },
  { name: "Chattogram–Satkania flood, Aug 2023", areas: ["satkania"], onset: "2023-08-06" },
  { name: "Brahmaputra–Jamuna flood, Jul 2004", areas: ["kurigram", "chilmari", "fulchhari", "islampur", "sirajganj"], onset: "2004-07-08" },
  { name: "Brahmaputra–Jamuna flood, Jul–Aug 2007", areas: ["kurigram", "chilmari", "fulchhari", "islampur", "sirajganj"], onset: "2007-07-31" },
  { name: "Sylhet–Sunamganj flash flood, May 2022", areas: ["sunamganj", "chhatak", "companiganj", "gowainghat"], onset: "2022-05-17" },
];

type Series = { time: string[]; value: number[] };

const rain: Record<string, Series> = {};
for (const p of rainPoints) rain[p.id] = await dailyRain(p, START, END);
const river: Record<string, Series> = {};
for (const a of areas.filter((x) => x.riverCell)) {
  const s: Series = await dailyDischarge(a.riverCell, Q_START, END);
  const i0 = s.time.indexOf(START);
  river[a.id] = { time: s.time.slice(i0), value: s.value.slice(i0) };
}
const days = rain[rainPoints[0].id].time;

const levels: Record<string, Level[]> = Object.fromEntries(areas.map((a) => [a.id, []]));
for (let i = 0; i < days.length; i++) {
  const win = (s: Series) => ({ observed: s.value.slice(Math.max(0, i - 6), i + 1), forecast: [] as number[] });
  const inputs: Inputs = {
    asOf: days[i], forecastAvailable: false, observedSource: "era5",
    rain: Object.fromEntries(Object.entries(rain).map(([k, s]) => [k, win(s)])),
    river: Object.fromEntries(Object.entries(river).map(([k, s]) => [k, win(s)])),
  };
  for (const a of areas) levels[a.id].push(assessArea(a, inputs, stations, rainThresholds, riverThresholds).level);
}

const years = Number(END.slice(0, 4)) - Number(START.slice(0, 4)) + 1;
const episodes = (ls: Level[]) => ls.filter((l, i) => l === 3 && (i === 0 || ls[i - 1] < 3)).length;

let md = `# Backtest results (${START} – ${END}, observations only)\n\n`;
md += "Generated by `scripts/backtest.mts`. Forecasts are not used, so this measures the observation-based part of Agam only.\n\n";
md += "## How often each area would reach Danger\n\n| Area | District | Danger episodes / year | Danger days / year | Warning-or-higher days / year |\n|---|---|---|---|---|\n";
for (const a of areas) {
  const ls = levels[a.id];
  md += `| ${a.name} | ${a.district} | ${(episodes(ls) / years).toFixed(1)} | ${(ls.filter((l) => l === 3).length / years).toFixed(1)} | ${(ls.filter((l) => l >= 2).length / years).toFixed(1)} |\n`;
}

md += "\n## Known floods: was Danger raised before onset?\n\nLead time = days between the first Danger in the 10 days up to onset (or 3 days after) and the onset date.\n\n| Event | Area | First Danger | Lead time |\n|---|---|---|---|\n";
let hits = 0;
let onTime = 0;
let total = 0;
for (const ev of EVENTS) {
  const o = days.indexOf(ev.onset);
  for (const id of ev.areas) {
    total++;
    const ls = levels[id];
    let first = -1;
    for (let i = o - 10; i <= o + 3; i++) if (ls[i] === 3) { first = i; break; }
    if (first >= 0) hits++;
    const lead = first >= 0 ? o - first : null;
    if (lead !== null && lead >= 0) onTime++;
    md += `| ${ev.name} | ${areas.find((a) => a.id === id)!.name} | ${first >= 0 ? days[first] : "— missed"} | ${lead === null ? "—" : lead >= 0 ? `${lead} day(s) before` : `${-lead} day(s) after`} |\n`;
  }
}
md += `\n**Danger on or before onset: ${onTime} of ${total} area-events. Within 3 days after onset: ${hits - onTime} more. Missed: ${total - hits}.**\n`;

const perArea = areas.map((a) => episodes(levels[a.id]) / years);
fs.writeFileSync(path.join(process.cwd(), "docs/evaluation-summary.json"), JSON.stringify({
  period: `${START.slice(0, 4)}–${END.slice(0, 4)}`,
  years,
  detected: hits,
  onTime,
  events: total,
  medianDangerEpisodesPerYear: [...perArea].sort((x, y) => x - y)[Math.floor(perArea.length / 2)],
}, null, 2));

fs.mkdirSync(path.join(process.cwd(), "docs"), { recursive: true });
fs.writeFileSync(path.join(process.cwd(), "docs/EVALUATION-results.md"), md);
console.log(md);
